# Generated by Django 2.2.16 on 2022-08-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('user', 'Пользователь'), ('anonymous', 'Аноним'), ('superuser', 'Суперюзер')], default='user', max_length=40, verbose_name='Роль пользователя'),
        ),
    ]
